import net.neoforged.moddevgradle.legacyforge.tasks.RemapJar
import proguard.gradle.ProGuardTask

import java.nio.charset.Charset
import java.nio.file.Files
import java.nio.file.StandardOpenOption

buildscript {
    repositories {
        maven { url = "https://plugins.gradle.org/m2/" }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.guardsquare:proguard-gradle:7.6.1'
    }
}

plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.+'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = 'com.elfmcys.yesstevemodel'
archivesBaseName = 'yesstevemodel-forge-1.20'

// 构建工具用到的变量
var buildDir = layout.buildDirectory.asFile.get().absolutePath
var builderPath = "${buildDir}/ysm-native/YSMBuilder.exe"
var buildTaskGroup = "ysm"
var buildModLoader = "forge"
var buildGameVersion = "1200"
var javaHome = System.properties['java.home']
var devOutputDir = "${buildDir}/devlibs"
var outputDir = "${buildDir}/libs"
var devLib = "${buildDir}/ysm-native/lib/ysm-core_${buildModLoader}-${buildGameVersion}-dev.dll"

var dictPath = file("${buildDir}/tmp/proguard/dict.txt").toPath()

if (!file(builderPath).exists()) {
    System.err.println("Please put YSMBuilder to ${builderPath}")
    throw new GradleException("YSMBuilder not found")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    version = "1.20.1-47.4.3"

    parchment {
        mappingsVersion = '+'
        minecraftVersion = '1.20.1'
    }

    // validateAccessTransformers = true
    // accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            jvmArguments = [
                    "-XX:+IgnoreUnrecognizedVMOptions",
                    "-XX:+AllowEnhancedClassRedefinition"
            ]
            // 以下环境变量只在调试时有效，在测试和生产构建中无效
            environment.putAll([
                    "EMBEDDED_MODEL_PATH": "${projectDir}\\src\\main\\resources\\assets\\yes_steve_model\\custom",
                    "YSM_CORE_LIB"       : devLib
            ])
        }

        client {
            client()
            gameDirectory = project.file('run/client_a')
        }

        client2 {
            client()
            gameDirectory = project.file('run/client_b')
            programArguments = ["--username", "tartaric_acid"]
        }

        server {
            server()
            gameDirectory = project.file('run/server')
        }
    }

    mods {
        yes_steve_model {
            sourceSet sourceSets.main
        }
    }
}

mixin {
    add sourceSets.main, "yes_steve_model.refmap.json"
    config "yes_steve_model.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

processResources {
    inputs.property "mod_version", project.version
    filteringCharset "UTF-8"
    outputs.upToDateWhen { false }

    filesMatching("META-INF/mods.toml") {
        expand "mod_version": project.version
    }
}

repositories {
    flatDir {
        dir 'libs'
    }
    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        // Add jitpack to repositories
        url 'https://jitpack.io'
    }
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    annotationProcessor 'io.github.llamalad7:mixinextras-common:0.3.6'
    compileOnly 'org.jetbrains:annotations:26.0.1'

    modCompileOnly 'libs:firstperson-forge:2.2.3-mc1.20'
    modCompileOnly 'libs:notenoughanimations-forge:1.6.4-mc1.20'
    modCompileOnly 'libs:oculus_legacy:mc1.20.1-1.6.13'
    modCompileOnly 'libs:oculus:mc1.20.1-1.7.0'
    modCompileOnly "curse.maven:embeddium-908741:${embeddium_id}"

    // 需要这样写，才能通过编译，并优先运行重锋
    modCompileOnly "maven.modrinth:slashblade-resharped:1.1.6-1.20.1"
    modCompileOnly "curse.maven:slashblade-241596:4789018"
    modRuntimeOnly "maven.modrinth:slashblade-resharped:1.1.6-1.20.1"

    modImplementation "curse.maven:carry-on-274259:${carry_on_id}"
    modImplementation "top.theillusivec4.curios:curios-forge:${curios_version}"
    modImplementation "curse.maven:caelus-308989:${caelus_id}"
    modImplementation "curse.maven:cosmetic-armor-reworked-237307:${cosmetic_armor_id}"
    modImplementation "curse.maven:elytra-slot-317716:${elytra_slot_id}"
    modImplementation "maven.modrinth:parcool:1.20.1-3.4.1.2-forge"
    modImplementation 'curse.maven:timeless-and-classics-zero-1028108:6654541-sources-6654543'

    // swem 需要
    modRuntimeOnly "curse.maven:playeranimator-658587:4587214"
    modImplementation "curse.maven:geckolib-388172:5460309"
    modImplementation "curse.maven:swem-582697:${swem_id}"

    // 女仆模组兼容
    modImplementation "curse.maven:touhou-little-maid-355044:6911704-sources-6911737"

    // 背包兼容
    modImplementation "maven.modrinth:sophisticated-core:1.20.1-1.2.0.843-forge"
    modImplementation "maven.modrinth:sophisticated-backpacks:1.20.1-3.23.1.1184-forge"

    // jade 和 top 信息显示
    modImplementation "maven.modrinth:jade:11.8.0-forge"
    modCompileOnly "curse.maven:the-one-probe-245211:4629624"

    // 卓越前线
    modImplementation "libs:superbwarfare-1.20.1:0.8.7.1-c6d401e0e"

    // 机械动力，兼容那个扳手
    modCompileOnly "maven.modrinth:create:1.20.1-6.0.6"

    // 引入 MixinExtras 以解决一些棘手的 Mixin 冲突问题（比如 @Redirect 不能嵌套）
    // Fabric / NeoForge 中自带 MixinExtras，无需打包
    modCompileOnly "io.github.llamalad7:mixinextras-common:0.3.6"
    jarJar(modImplementation("io.github.llamalad7:mixinextras-forge:0.3.6")) {
        version {
            strictly '[0.3.6,)'
            prefer '0.3.6'
        }
    }

    // 其他运行测试模组
    modRuntimeOnly "maven.modrinth:curtain:1.3.2-1.20.1"
    modRuntimeOnly "maven.modrinth:mantle:1.11.28"
    modRuntimeOnly "maven.modrinth:tinkers-construct:3.9.0.6"

    // modRuntimeOnly "maven.modrinth:cloth-config:11.1.136+forge"
    // modRuntimeOnly "maven.modrinth:better-combat:1.8.6+1.20.1-forge"
}

jar {
    manifest.attributes([
            "Implementation-Title"  : project.name,
            "Implementation-Version": "${version}",
            "MixinConfigs"          : "yes_steve_model.mixins.json"
    ])
    archiveClassifier = "raw"
}

afterEvaluate {
    tasks.reobfJar.outputs.upToDateWhen { false }
    tasks.reobfJar.destinationDirectory = tasks.jar.destinationDirectory
    tasks.reobfJar.archiveClassifier = ""
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += [
            '-Xlint:-removal'
    ]
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.register('buildDevLib', Exec) {
    description "runClient 之前需要手动运行此 task"
    group buildTaskGroup
    commandLine builderPath, 'build', projectDir, buildModLoader, buildGameVersion, 'dev', devLib
}

tasks.register('buildWindowsTestJar', Exec) {
    description "构建 Windows 版未混淆模组，仅供内部测试，不能以任何方式公开"
    group buildTaskGroup
    dependsOn tasks.reobfJar
    commandLine builderPath, 'build', projectDir, buildModLoader, buildGameVersion, 'win-test',
            tasks.reobfJar.archiveFile.get().asFile.absolutePath,
            '-l', tasks.reobfJar.remapOperation.mappings.first().absolutePath,
            '-o', outputDir
}

tasks.register('buildLinuxTestJar', Exec) {
    description "构建 Linux 版未混淆模组，仅供内部测试，不能以任何方式公开"
    group buildTaskGroup
    dependsOn tasks.reobfJar
    commandLine builderPath, 'build', projectDir, buildModLoader, buildGameVersion, 'linux-test',
            tasks.reobfJar.archiveFile.get().asFile.absolutePath,
            '-l', tasks.reobfJar.remapOperation.mappings.first().absolutePath,
            '-o', outputDir
}

tasks.register('tempJar', Jar) {
    manifest.from(tasks.jar.manifest)
    from tasks.jar.source

    destinationDirectory = tasks.jar.destinationDirectory
    archiveClassifier = tasks.jar.archiveClassifier
}

tasks.register('proguardJar', ProGuardTask) {
    dependsOn tasks.tempJar

    configuration file('proguard.pro')
    obfuscationdictionary(dictPath)
    classobfuscationdictionary(dictPath)
    packageobfuscationdictionary(dictPath)

    libraryjars "${javaHome}/jmods"
    libraryjars "${javaHome}/lib"
    libraryjars sourceSets.main.compileClasspath
    outputs.upToDateWhen { false }

    injars(tasks.tempJar.archiveFile)
    outjars(file("${devOutputDir}/${archivesBaseName}-${version}-proguard.jar"))
    printmapping("${outputDir}/${archivesBaseName}-${version}-mappings.txt")

    doFirst {
        var rand = new Random()
        var builder = new StringBuilder(24)
        Files.createDirectories(dictPath.parent)
        var writer = Files.newBufferedWriter(dictPath, Charset.forName("utf-8"), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)
        for (var line = 0; line < 1000; line++) {
            var num = rand.nextInt(0, 2)
            switch (num) {
                case 0: builder.append('O'); break
                case 1: builder.append('o'); break
                default: throw new Exception()
            }
            for (var i = 0; i < 23; i++) {
                num = rand.nextInt(0, 3)
                switch (num) {
                    case 0: builder.append('0'); break
                    case 1: builder.append('o'); break
                    case 2: builder.append('O'); break
                    default: throw new Exception()
                }
            }
            writer.writeLine(builder.toString())
            builder.delete(0, 24)
        }
        writer.close()
    }
}

tasks.register('reobfProguardJar', RemapJar) {
    dependsOn tasks.proguardJar
    outputs.upToDateWhen { false }

    input = tasks.proguardJar.outJarFileCollection.singleFile
    destinationDirectory = tasks.jar.destinationDirectory
    archiveBaseName = tasks.reobfJar.archiveBaseName
    archiveVersion = tasks.reobfJar.archiveVersion
    archiveClassifier = ""
    archiveAppendix = tasks.reobfJar.archiveAppendix
    libraries = tasks.reobfJar.libraries

    remapOperation.mappings = tasks.reobfJar.remapOperation.mappings
    remapOperation.toolType = tasks.reobfJar.remapOperation.toolType
    remapOperation.toolClasspath = tasks.reobfJar.remapOperation.toolClasspath
}

tasks.register('buildWindowsProductionJar', Exec) {
    description "构建经过混淆的模组，仅可用于 windows 端内测"
    group buildTaskGroup
    dependsOn tasks.reobfProguardJar
    outputs.upToDateWhen { false }

    commandLine builderPath, 'build', projectDir, buildModLoader, buildGameVersion, 'win-production',
            tasks.reobfProguardJar.archiveFile.get().asFile.absolutePath,
            '-p', "${projectDir}/ysm.vmp",
            '-l', tasks.reobfProguardJar.remapOperation.mappings.first().absolutePath,
            '-g', tasks.proguardJar.printMappingFile.path,
            '-o', outputDir
}

tasks.register('buildProductionJar', Exec) {
    description "构建经过混淆的模组，用于内测"
    group buildTaskGroup
    dependsOn tasks.reobfProguardJar
    outputs.upToDateWhen { false }

    commandLine builderPath, 'build', projectDir, buildModLoader, buildGameVersion, 'production',
            tasks.reobfProguardJar.archiveFile.get().asFile.absolutePath,
            '-p', "${projectDir}/ysm.vmp",
            '-l', tasks.reobfProguardJar.remapOperation.mappings.first().absolutePath,
            '-g', tasks.proguardJar.printMappingFile.path,
            '-o', outputDir
}

tasks.register('buildProductionSignedJar', Exec) {
    description "构建经过混淆的模组并签名，用于正式版发布"
    group buildTaskGroup
    dependsOn tasks.reobfProguardJar
    outputs.upToDateWhen { false }

    commandLine builderPath, 'build', projectDir, buildModLoader, buildGameVersion, 'production',
            tasks.reobfProguardJar.archiveFile.get().asFile.absolutePath,
            '-p', "${projectDir}/ysm.vmp",
            '-l', tasks.reobfProguardJar.remapOperation.mappings.first().absolutePath,
            '-g', tasks.proguardJar.printMappingFile.path,
            '-o', outputDir,
            '-s'
}
