import proguard.gradle.ProGuardTask

import java.nio.charset.Charset
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.nio.file.StandardOpenOption

buildscript {
    repositories {
        maven { url = "https://plugins.gradle.org/m2/" }
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.gradle.toolchains:foojay-resolver:0.5.0'
        classpath 'org.parchmentmc:librarian:1.+'
        classpath 'com.guardsquare:proguard-gradle:7.3.1'
        classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
    }
}


plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}
apply plugin: 'org.spongepowered.mixin'

version = mod_version
group = 'com.elfmcys.yesstevemodel'
archivesBaseName = 'yesstevemodel-forge-1.20'

// 构建工具用到的变量
var builderPath = "${buildDir}/ysm-native/YSMBuilder.exe"
var buildTaskGroup = "ysm"
var buildModLoader = "forge"
var buildGameVersion = "1200"
var javaHome = System.properties['java.home']
var devLib = "${buildDir}/ysm-native/lib/ysm-core_forge-1200-dev.dll"

var dictPath = file("${buildDir}/tmp/proguard/dict.txt").toPath()

if (!file(builderPath).exists()) {
    System.err.println("Please put YSMBuilder to ${builderPath}")
    throw new GradleException("YSMBuilder not found")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment', version: '2023.08.20-1.20.1'

    copyIdeResources = true

    // accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            jvmArgs "-XX:+IgnoreUnrecognizedVMOptions"
            jvmArgs "-XX:+AllowEnhancedClassRedefinition"
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'yesstevemodel'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            // 以下环境变量只在调试时有效，在测试和生产构建中无效
            buildEnvironment {
                environment 'EMBEDDED_MODEL_PATH', "${projectDir}\\src\\main\\resources\\assets\\yes_steve_model\\custom"
                environment 'YSM_CORE_LIB', devLib
            }

            mods {
                yes_steve_model {
                    source sourceSets.main
                }
            }
        }

        client {
            workingDirectory project.file('run/client_a')
        }

        client2 {
            parent minecraft.runs.client
            workingDirectory project.file('run/client_b')
            args '--username', 'tartaric_acid'
        }

        server {
            workingDirectory project.file('run/server')
        }
    }
}

mixin {
    add sourceSets.main, "yes_steve_model.refmap.json"
    config "yes_steve_model.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    flatDir {
        dir 'libs'
    }
    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        // Add jitpack to repositories
        url 'https://jitpack.io'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.1.0'
    implementation fg.deobf('libs:firstperson-forge:2.2.3-mc1.20')
    implementation fg.deobf('libs:notenoughanimations-forge:1.6.4-mc1.20')
    compileOnly fg.deobf('libs:embeddium:0.2.18+mc1.20.1')
    compileOnly fg.deobf('libs:oculus_legacy:mc1.20.1-1.6.13')
    compileOnly fg.deobf('libs:oculus:mc1.20.1-1.7.0')
    implementation fg.deobf("curse.maven:slashblade-241596:${slashblade_id}")
    implementation fg.deobf("curse.maven:carry-on-274259:${carry_on_id}")
    implementation fg.deobf("curse.maven:curios-309927:${curios_id}")
    implementation fg.deobf("curse.maven:caelus-308989:${caelus_id}")
    implementation fg.deobf("curse.maven:cosmetic-armor-reworked-237307:${cosmetic_armor_id}")
    implementation fg.deobf("curse.maven:elytra-slot-317716:${elytra_slot_id}")
    implementation fg.deobf("curse.maven:parcool-482378:${parcool_id}")
    implementation fg.deobf('curse.maven:timeless-and-classics-zero-1028108:5529117-sources-5529578')
    // swem 需要
    runtimeOnly fg.deobf("curse.maven:playeranimator-658587:4587214")
    runtimeOnly fg.deobf("curse.maven:geckolib-388172:5460309")
    implementation fg.deobf("curse.maven:swem-582697:${swem_id}")
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    manifest {
        attributes([
                "Implementation-Title"  : project.name,
                "Implementation-Version": "${version}"
        ])
    }
    outputs.upToDateWhen { false }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.register('buildDevLib', Exec) {
    description "runClient 之前需要手动运行此 task"
    group buildTaskGroup
    commandLine builderPath, 'build', javaHome, projectDir, buildModLoader, buildGameVersion, 'dev', devLib
}

tasks.register('buildWindowsTestJar', Exec) {
    description "构建 Windows 版未混淆模组，仅供内部测试，不能以任何方式公开"
    group buildTaskGroup
    dependsOn tasks.reobfJar
    commandLine builderPath, 'build', javaHome, projectDir, buildModLoader, buildGameVersion, 'win-test',
            tasks.reobfJar.input.asFile.get().path,
            '-l', tasks.createMcpToSrg.output.asFile.get().path
}

tasks.register('buildLinuxTestJar', Exec) {
    description "构建 Linux 版未混淆模组，仅供内部测试，不能以任何方式公开"
    group buildTaskGroup
    dependsOn tasks.reobfJar
    commandLine builderPath, 'build', javaHome, projectDir, buildModLoader, buildGameVersion, 'linux-test',
            tasks.reobfJar.input.asFile.get().path,
            '-l', tasks.createMcpToSrg.output.asFile.get().path
}

tasks.register('tempJar', Jar) {
    manifest.from(tasks.jar.manifest)
    from tasks.jar.source
    outputs.upToDateWhen { false }

    destinationDirectory.set(file("${buildDir}/tmp"))
    archiveClassifier.set("temp")
    finalizedBy tasks.proguardJar
}

reobf {
    tempJar {}
}

tasks.register('proguardJar', ProGuardTask) {
    configuration file('proguard.pro')
    obfuscationdictionary(dictPath)
    classobfuscationdictionary(dictPath)
    packageobfuscationdictionary(dictPath)

    libraryjars "${javaHome}/jmods"
    libraryjars "${javaHome}/lib"
    libraryjars sourceSets.main.compileClasspath
    outputs.upToDateWhen { false }

    injars(tasks.tempJar.archiveFile.get())
    outjars(file("${buildDir}/libs/${archivesBaseName}-${version}-minified.jar"))
    printmapping("${buildDir}/libs/${archivesBaseName}-${version}-mappings.txt")

    doFirst {
        var rand = new Random()
        var builder = new StringBuilder(24)
        Files.createDirectories(dictPath.parent)
        var writer = Files.newBufferedWriter(dictPath, Charset.forName("utf-8"), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)
        for (var line = 0; line < 1000; line++) {
            var num = rand.nextInt(0, 2)
            switch (num) {
                case 0: builder.append('O'); break
                case 1: builder.append('o'); break
                default: throw new Exception()
            }
            for (var i = 0; i < 23; i++) {
                num = rand.nextInt(0, 3)
                switch (num) {
                    case 0: builder.append('0'); break
                    case 1: builder.append('o'); break
                    case 2: builder.append('O'); break
                    default: throw new Exception()
                }
            }
            writer.writeLine(builder.toString())
            builder.delete(0, 24)
        }
        writer.close()
    }
    doLast {
        Files.move(outJarFileCollection.singleFile.toPath(),
                inJarFileCollection.singleFile.toPath(),
                StandardCopyOption.REPLACE_EXISTING)
    }
}

tasks.register('buildWindowsProductionJar', Exec) {
    doFirst {
        Files.move(tempJar.archiveFile.get().asFile.toPath(),
                tasks.proguardJar.outJarFileCollection.singleFile.toPath(),
                StandardCopyOption.REPLACE_EXISTING)
    }

    description "构建经过混淆的模组，仅可用于 windows 端内测"
    group buildTaskGroup
    dependsOn tasks.reobfTempJar
    outputs.upToDateWhen { false }

    commandLine builderPath, 'build', javaHome, projectDir, buildModLoader, buildGameVersion, 'win-production',
            tasks.proguardJar.outJarFileCollection.singleFile.path,
            '-p', "${projectDir}/ysm.vmp",
            '-l', tasks.createMcpToSrg.output.asFile.get().path,
            '-g', tasks.proguardJar.printMappingFile.path
}

tasks.register('buildProductionJar', Exec) {
    doFirst {
        Files.move(tempJar.archiveFile.get().asFile.toPath(),
                tasks.proguardJar.outJarFileCollection.singleFile.toPath(),
                StandardCopyOption.REPLACE_EXISTING)
    }

    description "构建经过混淆的模组，用于内测"
    group buildTaskGroup
    dependsOn tasks.reobfTempJar
    outputs.upToDateWhen { false }

    commandLine builderPath, 'build', javaHome, projectDir, buildModLoader, buildGameVersion, 'production',
            tasks.proguardJar.outJarFileCollection.singleFile.path,
            '-p', "${projectDir}/ysm.vmp",
            '-l', tasks.createMcpToSrg.output.asFile.get().path,
            '-g', tasks.proguardJar.printMappingFile.path
}

tasks.register('buildProductionSignedJar', Exec) {
    doFirst {
        Files.move(tempJar.archiveFile.get().asFile.toPath(),
                tasks.proguardJar.outJarFileCollection.singleFile.toPath(),
                StandardCopyOption.REPLACE_EXISTING)
    }

    description "构建经过混淆的模组并签名，用于正式版发布"
    group buildTaskGroup
    dependsOn tasks.reobfTempJar
    outputs.upToDateWhen { false }

    commandLine builderPath, 'build', javaHome, projectDir, buildModLoader, buildGameVersion, 'production',
            tasks.proguardJar.outJarFileCollection.singleFile.path,
            '-p', "${projectDir}/ysm.vmp",
            '-l', tasks.createMcpToSrg.output.asFile.get().path,
            '-g', tasks.proguardJar.printMappingFile.path,
            '-s'
}